name: is-2612-group

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: group
      POSTGRES_PASSWORD: group
      POSTGRES_DB: group_system
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U group -d group_system']
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  postgres_data:
